name: Deploy to Pis
on:
  push:
    branches: [dev]
      paths-ignore:
      - 'PROJECT_LOG.md'
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Pi1
            port: 2222
            username: isaac_1
            key: ${{ secrets.PI5_SSH_KEY }}
          - name: Pi2
            port: 2223
            username: isaac_2
            key: ${{ secrets.PI_SSH_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to ${{ matrix.name }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          port: ${{ matrix.port }}
          username: ${{ matrix.username }}
          key: ${{ secrets[matrix.key] }}
          script: |
            cd ~/project-vesper

            git pull origin dev
            docker-compose down
            docker-compose up -d --build