
# Base image - use official Postgres image
# Remember: this is also Debian Linux + PostgreSQL
FROM postgres:latest

# Install nano
RUN apt-get update && apt-get install -y nano && rm -rf /var/lib/apt/lists/*

# Can add further customizations below later