"""empty message

Revision ID: 0a4f03334cb0
Revises: e6625eaec776
Create Date: 2026-01-21 22:00:51.560604+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4f03334cb0'
down_revision: Union[str, None] = 'e6625eaec776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habits', 'pillar_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habits', 'pillar_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
