"""add nutrition info fields to Product

Revision ID: 0e8b19461a4d
Revises: 24572d9b9df9
Create Date: 2026-03-13 19:30:05.985595+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8b19461a4d'
down_revision: Union[str, None] = '24572d9b9df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('protein_per_100g', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('fat_per_100g', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('carbs_per_100g', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('fat_mono_per_100g', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('fat_poly_per_100g', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('fat_sat_per_100g', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('carbs_fiber_per_100g', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('carbs_sugar_per_100g', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('sodium_per_100g', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('potassium_per_100g', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'potassium_per_100g')
    op.drop_column('products', 'sodium_per_100g')
    op.drop_column('products', 'carbs_sugar_per_100g')
    op.drop_column('products', 'carbs_fiber_per_100g')
    op.drop_column('products', 'fat_sat_per_100g')
    op.drop_column('products', 'fat_poly_per_100g')
    op.drop_column('products', 'fat_mono_per_100g')
    op.drop_column('products', 'carbs_per_100g')
    op.drop_column('products', 'fat_per_100g')
    op.drop_column('products', 'protein_per_100g')
    # ### end Alembic commands ###
