"""purging leetcode records

Revision ID: 141674d969ac
Revises: 7a737310e2ba
Create Date: 2026-07-10 02:18:09.596343+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '141674d969ac'
down_revision: Union[str, None] = '7a737310e2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leetcode_records')
    sa.Enum(name="difficulty_enum").drop(op.get_bind())
    sa.Enum(name="language_enum").drop(op.get_bind())
    sa.Enum(name="lcstatus_enum").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leetcode_records',
    sa.Column('leetcode_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('difficulty', postgresql.ENUM('easy', 'medium', 'hard', name='difficulty_enum'), autoincrement=False, nullable=False),
    sa.Column('language', postgresql.ENUM('python', 'js', 'cpp', 'c', 'go', name='language_enum'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('solved', 'attempted', 'reviewed', name='lcstatus_enum'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('entry_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leet_code_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leet_code_records'))
    )
    # ### end Alembic commands ###
