"""Add created_at field to DailyIntention

Revision ID: 19984518b2de
Revises: 9ca489d2aabc
Create Date: 2025-06-06 14:20:14.749889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19984518b2de'
down_revision: Union[str, None] = '9ca489d2aabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_intention', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_intention', 'created_at')
    # ### end Alembic commands ###
