"""revisit pillar model, add join tables for habits, tasks, time_entries

Revision ID: 1ae36cd43143
Revises: fde91e6d30df
Create Date: 2026-03-04 02:02:18.832933+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae36cd43143'
down_revision: Union[str, None] = 'fde91e6d30df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_pillars',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('pillar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], name=op.f('fk_task_pillars_pillar_id_pillars')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_pillars_task_id_tasks')),
    sa.PrimaryKeyConstraint('task_id', 'pillar_id', name=op.f('pk_task_pillars'))
    )
    op.create_table('time_entry_pillars',
    sa.Column('time_entry_id', sa.Integer(), nullable=False),
    sa.Column('pillar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], name=op.f('fk_time_entry_pillars_pillar_id_pillars')),
    sa.ForeignKeyConstraint(['time_entry_id'], ['time_entries.id'], name=op.f('fk_time_entry_pillars_time_entry_id_time_entries')),
    sa.PrimaryKeyConstraint('time_entry_id', 'pillar_id', name=op.f('pk_time_entry_pillars'))
    )
    op.create_table('habit_pillars',
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('pillar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('fk_habit_pillars_habit_id_habits')),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], name=op.f('fk_habit_pillars_pillar_id_pillars')),
    sa.PrimaryKeyConstraint('habit_id', 'pillar_id', name=op.f('pk_habit_pillars'))
    )
    op.create_unique_constraint(op.f('uq_pillars_name'), 'pillars', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_pillars_name'), 'pillars', type_='unique')
    op.drop_table('habit_pillars')
    op.drop_table('time_entry_pillars')
    op.drop_table('task_pillars')
    # ### end Alembic commands ###
