"""Add category field to Habit model

Revision ID: 2033f0278826
Revises: e5026ac2b998
Create Date: 2025-06-18 20:19:57.387463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2033f0278826'
down_revision: Union[str, None] = 'e5026ac2b998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('category', sa.String(length=255), nullable=False, server_default='misc'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'category')
    # ### end Alembic commands ###
