"""2025_11_5 Add city, country, & units to User model

Revision ID: 213c71a1b8db
Revises: 56576be3a0b4
Create Date: 2025-11-05 13:50:36.646049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213c71a1b8db'
down_revision: Union[str, None] = '56576be3a0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE unit_system_enum AS ENUM ('metric', 'imperial')")
    op.add_column('users', sa.Column('city', sa.String(length=100), server_default='Chicago', nullable=False))
    op.add_column('users', sa.Column('country', sa.String(length=3), server_default='US', nullable=False))
    op.add_column('users', sa.Column('units', sa.Enum('metric', 'imperial', name='unit_system_enum'), server_default='imperial', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'units')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
