"""remove weight_units, weight_requires_units constraint, weight_units_enum

Revision ID: 24572d9b9df9
Revises: 951066900f24
Create Date: 2026-03-09 22:55:51.619726+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24572d9b9df9'
down_revision: Union[str, None] = '951066900f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_daily_metrics_weight_requires_units", "daily_metrics")
    op.drop_column('daily_metrics', 'weight_units')
    op.execute("DROP TYPE weight_units_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE weight_units_enum AS ENUM ('lbs', 'kg')")
    op.add_column('daily_metrics', sa.Column('weight_units', postgresql.ENUM('lbs', 'kg', name='weight_units_enum'), autoincrement=False, nullable=True))
    op.execute("UPDATE daily_metrics SET weight_units = 'kg' WHERE weight IS NOT NULL")
    op.create_check_constraint('weight_requires_units', 'daily_metrics', '(weight IS NULL AND weight_units IS NULL) OR (weight IS NOT NULL AND weight_units IS NOT NULL)')
    # ### end Alembic commands ###
