"""Remove server defaults (oops)

Revision ID: 480dce69f58d
Revises: 77bba107df6b
Create Date: 2025-07-31 11:56:33.233033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '480dce69f58d'
down_revision: Union[str, None] = '77bba107df6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name', server_default=None)
    op.alter_column('user', 'role', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=50), nullable=False, server_default='user'))
    op.add_column('user', sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))
    # ### end Alembic commands ###
