"""2025_11_2 add ABTest, ABVariant

Revision ID: 56576be3a0b4
Revises: 985949b21670
Create Date: 2025-11-02 11:10:27.208660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56576be3a0b4'
down_revision: Union[str, None] = '985949b21670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_tests',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('hypothesis', sa.String(length=100), nullable=False),
    sa.Column('variant_a_label', sa.String(length=50), nullable=False),
    sa.Column('variant_b_label', sa.String(length=50), nullable=False),
    sa.Column('success_condition', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ab_tests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_tests'))
    )
    op.create_table('ab_trials',
    sa.Column('abtest_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.Enum('A', 'B', name='abvariantenum'), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['abtest_id'], ['ab_tests.id'], name=op.f('fk_ab_trials_abtest_id_ab_tests')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ab_trials_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_trials'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ab_trials')
    op.drop_table('ab_tests')
    # ### end Alembic commands ###
