"""add indexes for several models

Revision ID: 57bbdb85c80e
Revises: 841698217cd9
Create Date: 2026-03-24 01:39:20.491303+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57bbdb85c80e'
down_revision: Union[str, None] = '841698217cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_habit_completions_user_habit_completed_at', 'habit_completions', ['user_id', 'habit_id', 'completed_at'], unique=False)
    op.create_index('ix_nutrition_logs_user_entry_datetime', 'nutrition_logs', ['user_id', 'entry_datetime'], unique=False)
    op.create_index('ix_products_user_deleted_at', 'products', ['user_id', 'deleted_at'], unique=False)
    op.create_index('ix_tasks_user_due_date', 'tasks', ['user_id', 'due_date'], unique=False)
    op.create_index('ix_time_entries_user_started_at', 'time_entries', ['user_id', 'started_at'], unique=False)
    op.create_index('ix_transactions_user_created_at', 'transactions', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_created_at', table_name='transactions')
    op.drop_index('ix_time_entries_user_started_at', table_name='time_entries')
    op.drop_index('ix_tasks_user_due_date', table_name='tasks')
    op.drop_index('ix_products_user_deleted_at', table_name='products')
    op.drop_index('ix_nutrition_logs_user_entry_datetime', table_name='nutrition_logs')
    op.drop_index('ix_habit_completions_user_habit_completed_at', table_name='habit_completions')
    # ### end Alembic commands ###
