"""add nutrition log to groceries

Revision ID: 5cdf18e58c67
Revises: 99d0a501b1f3
Create Date: 2026-03-08 04:44:06.628627+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdf18e58c67'
down_revision: Union[str, None] = '99d0a501b1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_logs',
    sa.Column('entry_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meal', sa.Enum('breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'supper', 'pm_snack', name='meal_enum'), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat_mono', sa.Float(), nullable=True),
    sa.Column('fat_poly', sa.Float(), nullable=True),
    sa.Column('fat_sat', sa.Float(), nullable=True),
    sa.Column('carbs_fiber', sa.Float(), nullable=True),
    sa.Column('carbs_sugar', sa.Float(), nullable=True),
    sa.Column('sodium', sa.Float(), nullable=True),
    sa.Column('potassium', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_nutrition_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_logs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutrition_logs')
    # ### end Alembic commands ###
