"""add shoppingtrip for transaction batches

Revision ID: 5fbd6c306476
Revises: d60aeaa2c254
Create Date: 2026-03-13 21:35:45.047113+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fbd6c306476'
down_revision: Union[str, None] = 'd60aeaa2c254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_trips',
    sa.Column('entry_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('store_name', sa.String(length=50), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shopping_trips_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_trips'))
    )
    op.add_column('transactions', sa.Column('shopping_trip_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_transactions_shopping_trip_id_shopping_trips'), 'transactions', 'shopping_trips', ['shopping_trip_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transactions_shopping_trip_id_shopping_trips'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'shopping_trip_id')
    op.drop_table('shopping_trips')
    # ### end Alembic commands ###
