"""fix missing or broken relationship cascades

Revision ID: 618dfe67bac1
Revises: 4813d8fa6ac3
Create Date: 2026-07-17 06:01:15.049054+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618dfe67bac1'
down_revision: Union[str, None] = '4813d8fa6ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_habit_completions_habit_id_habits'), 'habit_completions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_habit_completions_habit_id_habits'), 'habit_completions', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_recipe_ingredients_recipe_id_recipes'), 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(op.f('fk_recipe_ingredients_recipe_id_recipes'), 'recipe_ingredients', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_shopping_list_items_shopping_list_id_shopping_lists'), 'shopping_list_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shopping_list_items_shopping_list_id_shopping_lists'), 'shopping_list_items', 'shopping_lists', ['shopping_list_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_transactions_shopping_trip_id_shopping_trips'), 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transactions_shopping_trip_id_shopping_trips'), 'transactions', 'shopping_trips', ['shopping_trip_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_transactions_shopping_trip_id_shopping_trips'), 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transactions_shopping_trip_id_shopping_trips'), 'transactions', 'shopping_trips', ['shopping_trip_id'], ['id'])
    op.drop_constraint(op.f('fk_shopping_list_items_shopping_list_id_shopping_lists'), 'shopping_list_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shopping_list_items_shopping_list_id_shopping_lists'), 'shopping_list_items', 'shopping_lists', ['shopping_list_id'], ['id'])
    op.drop_constraint(op.f('fk_recipe_ingredients_recipe_id_recipes'), 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(op.f('fk_recipe_ingredients_recipe_id_recipes'), 'recipe_ingredients', 'recipes', ['recipe_id'], ['id'])
    op.drop_constraint(op.f('fk_habit_completions_habit_id_habits'), 'habit_completions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_habit_completions_habit_id_habits'), 'habit_completions', 'habits', ['habit_id'], ['id'])
    # ### end Alembic commands ###
