"""rename leet_code_records to leetcode_records

Revision ID: 7040c9022897
Revises: ffd311d8eaae
Create Date: 2026-06-14 23:06:55.998113+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7040c9022897'
down_revision: Union[str, None] = 'ffd311d8eaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('leet_code_records', 'leetcode_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('leetcode_records', 'leet_code_records')
    # ### end Alembic commands ###
