"""Add Recipe and RecipeIngredient models

Revision ID: 79c90364673d
Revises: d6f785b5f77b
Create Date: 2026-02-03 21:23:50.439656+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c90364673d'
down_revision: Union[str, None] = 'd6f785b5f77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('yields', sa.Float(), nullable=False),
    sa.Column('yields_units', sa.Enum('G', 'KG', 'OZ', 'LB', 'ML', 'L', 'FL_OZ', 'EA', name='unitenum'), server_default='G', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('yields > 0', name=op.f('ck_recipes_ck_recipe_yields_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes'))
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount_value', sa.Float(), nullable=False),
    sa.Column('amount_units', sa.Enum('G', 'KG', 'OZ', 'LB', 'ML', 'L', 'FL_OZ', 'EA', name='unitenum'), server_default='G', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_value > 0', name=op.f('ck_recipe_ingredients_ck_recipe_ingredient_amount_value_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_recipe_ingredients_product_id_products')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_ingredients_recipe_id_recipes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recipe_ingredients_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredients')
    op.drop_table('recipes')
    # ### end Alembic commands ###
