"""Add transaction id nullable col for ledger reversals

Revision ID: 7a737310e2ba
Revises: 2871ad31fb98
Create Date: 2026-07-08 04:13:42.971157+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a737310e2ba'
down_revision: Union[str, None] = '2871ad31fb98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_ledgers', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_inventory_ledgers_transaction_id_transactions'), 'inventory_ledgers', 'transactions', ['transaction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_inventory_ledgers_transaction_id_transactions'), 'inventory_ledgers', type_='foreignkey')
    op.drop_column('inventory_ledgers', 'transaction_id')
    # ### end Alembic commands ###
