"""add cascade to *_pillars association tables

Revision ID: 7dd05acb7fb9
Revises: 55d29346f6d4
Create Date: 2026-07-16 06:30:22.921365+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd05acb7fb9'
down_revision: Union[str, None] = '55d29346f6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_habit_pillars_habit_id_habits'), 'habit_pillars', type_='foreignkey')
    op.drop_constraint(op.f('fk_habit_pillars_pillar_id_pillars'), 'habit_pillars', type_='foreignkey')
    op.create_foreign_key(op.f('fk_habit_pillars_habit_id_habits'), 'habit_pillars', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_habit_pillars_pillar_id_pillars'), 'habit_pillars', 'pillars', ['pillar_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_habit_tags_tag_id_tags'), 'habit_tags', type_='foreignkey')
    op.drop_constraint(op.f('fk_habit_tags_habit_id_habits'), 'habit_tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_habit_tags_tag_id_tags'), 'habit_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_habit_tags_habit_id_habits'), 'habit_tags', 'habits', ['habit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_task_pillars_task_id_tasks'), 'task_pillars', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_pillars_pillar_id_pillars'), 'task_pillars', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_pillars_task_id_tasks'), 'task_pillars', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_task_pillars_pillar_id_pillars'), 'task_pillars', 'pillars', ['pillar_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_task_tags_task_id_tasks'), 'task_tags', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_tags_tag_id_tags'), 'task_tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_tags_tag_id_tags'), 'task_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_task_tags_task_id_tasks'), 'task_tags', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_time_entry_pillars_time_entry_id_time_entries'), 'time_entry_pillars', type_='foreignkey')
    op.drop_constraint(op.f('fk_time_entry_pillars_pillar_id_pillars'), 'time_entry_pillars', type_='foreignkey')
    op.create_foreign_key(op.f('fk_time_entry_pillars_pillar_id_pillars'), 'time_entry_pillars', 'pillars', ['pillar_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_time_entry_pillars_time_entry_id_time_entries'), 'time_entry_pillars', 'time_entries', ['time_entry_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_time_entry_pillars_time_entry_id_time_entries'), 'time_entry_pillars', type_='foreignkey')
    op.drop_constraint(op.f('fk_time_entry_pillars_pillar_id_pillars'), 'time_entry_pillars', type_='foreignkey')
    op.create_foreign_key(op.f('fk_time_entry_pillars_pillar_id_pillars'), 'time_entry_pillars', 'pillars', ['pillar_id'], ['id'])
    op.create_foreign_key(op.f('fk_time_entry_pillars_time_entry_id_time_entries'), 'time_entry_pillars', 'time_entries', ['time_entry_id'], ['id'])
    op.drop_constraint(op.f('fk_task_tags_task_id_tasks'), 'task_tags', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_tags_tag_id_tags'), 'task_tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_tags_tag_id_tags'), 'task_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('fk_task_tags_task_id_tasks'), 'task_tags', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(op.f('fk_task_pillars_pillar_id_pillars'), 'task_pillars', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_pillars_task_id_tasks'), 'task_pillars', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_pillars_pillar_id_pillars'), 'task_pillars', 'pillars', ['pillar_id'], ['id'])
    op.create_foreign_key(op.f('fk_task_pillars_task_id_tasks'), 'task_pillars', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(op.f('fk_habit_tags_habit_id_habits'), 'habit_tags', type_='foreignkey')
    op.drop_constraint(op.f('fk_habit_tags_tag_id_tags'), 'habit_tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_habit_tags_habit_id_habits'), 'habit_tags', 'habits', ['habit_id'], ['id'])
    op.create_foreign_key(op.f('fk_habit_tags_tag_id_tags'), 'habit_tags', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(op.f('fk_habit_pillars_pillar_id_pillars'), 'habit_pillars', type_='foreignkey')
    op.drop_constraint(op.f('fk_habit_pillars_habit_id_habits'), 'habit_pillars', type_='foreignkey')
    op.create_foreign_key(op.f('fk_habit_pillars_pillar_id_pillars'), 'habit_pillars', 'pillars', ['pillar_id'], ['id'])
    op.create_foreign_key(op.f('fk_habit_pillars_habit_id_habits'), 'habit_pillars', 'habits', ['habit_id'], ['id'])
    # ### end Alembic commands ###
