"""empty message

Revision ID: 83ed6bf2fb12
Revises: 0a4f03334cb0
Create Date: 2026-01-21 23:20:15.907180+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83ed6bf2fb12'
down_revision: Union[str, None] = '0a4f03334cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_metrics', sa.Column('wake_datetime', sa.DateTime(timezone=True), nullable=True))
    op.add_column('daily_metrics', sa.Column('sleep_datetime', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('daily_metrics', 'sleep_time')
    op.drop_column('daily_metrics', 'wake_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_metrics', sa.Column('wake_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('daily_metrics', sa.Column('sleep_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('daily_metrics', 'sleep_datetime')
    op.drop_column('daily_metrics', 'wake_datetime')
    # ### end Alembic commands ###
