"""add entry_datetime to lcrecord, completed_at to habit completion

Revision ID: 841698217cd9
Revises: c128849b7d68
Create Date: 2026-03-24 01:15:16.495736+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841698217cd9'
down_revision: Union[str, None] = 'c128849b7d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leet_code_records', sa.Column('entry_datetime', sa.DateTime(timezone=True), nullable=True))
    op.execute('UPDATE leet_code_records SET entry_datetime = created_at WHERE entry_datetime IS NULL')
    op.alter_column('leet_code_records', 'entry_datetime', nullable=False)
    
    # op.add_column('habit_completions', sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('habit_completions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.execute('UPDATE habit_completions SET completed_at = created_at WHERE completed_at IS NULL')
    op.alter_column('habit_completions', 'completed_at', nullable=False, server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leet_code_records', 'entry_datetime')
    op.drop_column('habit_completions', 'completed_at')
    # ### end Alembic commands ###
