"""add sort_key to task model for reordering

Revision ID: 895b04060fbe
Revises: 57bbdb85c80e
Create Date: 2026-05-09 21:20:57.301815+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.shared.fractional_indexing import generate_n_keys_between


# revision identifiers, used by Alembic.
revision: str = '895b04060fbe'
down_revision: Union[str, None] = '57bbdb85c80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add sort_key as nullable
    op.add_column('tasks', sa.Column('sort_key', sa.String(), nullable=True))

    # Backfill -> query all existing tasks in some order, generate N keys, write them back
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id FROM tasks ORDER BY id")).fetchall()
    task_ids = [r.id for r in rows]
    keys = generate_n_keys_between(None, None, len(task_ids))

    for task_id, key in zip(task_ids, keys):
        conn.execute(
            sa.text("UPDATE tasks SET sort_key = :key WHERE id = :id"),
            {"key": key, "id": task_id}
        )

    # Alter column to nullable=False
    op.alter_column('tasks', 'sort_key', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'sort_key')
    # ### end Alembic commands ###
