"""add inventoryledger, productinventory models for tracking inventory changes/state

Revision ID: 9648d29cb083
Revises: 0e8b19461a4d
Create Date: 2026-03-13 21:01:27.727977+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9648d29cb083'
down_revision: Union[str, None] = '0e8b19461a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_ledgers',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_delta', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('purchase', 'consumption', 'correction', 'waste', name='inventory_event_type_enum'), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_ledgers_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inventory_ledgers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_ledgers'))
    )
    op.create_index('ix_inventory_ledger_product_created', 'inventory_ledgers', ['product_id', 'created_at'], unique=False)
    op.create_table('product_inventories',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty_on_hand', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_inventories_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_product_inventories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_inventories')),
    sa.UniqueConstraint('product_id', name=op.f('uq_product_inventories_product_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_inventories')
    op.drop_index('ix_inventory_ledger_product_created', table_name='inventory_ledgers')
    op.drop_table('inventory_ledgers')
    # ### end Alembic commands ###
