"""remove hanging pillar_id field

Revision ID: 99d0a501b1f3
Revises: 1ae36cd43143
Create Date: 2026-03-05 19:42:14.713156+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d0a501b1f3'
down_revision: Union[str, None] = '1ae36cd43143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_habits_pillar_id_pillars'), 'habits', type_='foreignkey')
    op.drop_column('habits', 'pillar_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('pillar_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_habits_pillar_id_pillars'), 'habits', 'pillars', ['pillar_id'], ['id'])
    # ### end Alembic commands ###
