"""Add Habit & HabitCompletion models, remove is_anchor from Task accordingly

Revision ID: 9c378a042e1d
Revises: acfc062ee54b
Create Date: 2025-05-30 16:09:39.307466

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9c378a042e1d'
down_revision: Union[str, None] = 'acfc062ee54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('experimental_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('established_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promotion_threshold', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('habit_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('tasks', 'is_anchor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_anchor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('habit_completions')
    op.drop_table('habits')
    # ### end Alembic commands ###
