"""Add DailyIntention & DailyMetric models

Revision ID: 9ca489d2aabc
Revises: 9c378a042e1d
Create Date: 2025-06-06 12:49:28.243324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca489d2aabc'
down_revision: Union[str, None] = '9c378a042e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_intention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intention', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_metric')
    op.drop_table('daily_intention')
    # ### end Alembic commands ###
