"""Clean migration to base class (working version)

Revision ID: ab2b6db1da10
Revises: a33a63e3d33d
Create Date: 2025-06-09 17:07:01.621268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2b6db1da10'
down_revision: Union[str, None] = 'a33a63e3d33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habitcompletion', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habitcompletion', 'completed_at')
    # ### end Alembic commands ###
