"""add task_links association table, relationships for sub/supertasks

Revision ID: c09c7a73ab1e
Revises: 79c90364673d
Create Date: 2026-02-18 21:37:48.017602+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09c7a73ab1e'
down_revision: Union[str, None] = '79c90364673d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_links',
    sa.Column('subtask_id', sa.Integer(), nullable=False),
    sa.Column('supertask_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subtask_id'], ['tasks.id'], name=op.f('fk_task_links_subtask_id_tasks')),
    sa.ForeignKeyConstraint(['supertask_id'], ['tasks.id'], name=op.f('fk_task_links_supertask_id_tasks')),
    sa.PrimaryKeyConstraint('subtask_id', 'supertask_id', name=op.f('pk_task_links'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_links')
    # ### end Alembic commands ###
