"""remove ab_tests & ab_trials tables

Revision ID: c77d567dce10
Revises: 0bcefc75a41c
Create Date: 2026-01-02 20:17:03.060761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c77d567dce10'
down_revision: Union[str, None] = '0bcefc75a41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ab_trials')
    op.drop_table('ab_tests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_trials',
    sa.Column('abtest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('variant', postgresql.ENUM('A', 'B', name='abvariantenum'), autoincrement=False, nullable=False),
    sa.Column('is_success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['abtest_id'], ['ab_tests.id'], name=op.f('fk_ab_trials_abtest_id_ab_tests')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ab_trials_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_trials'))
    )
    op.create_table('ab_tests',
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('hypothesis', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('variant_a_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('variant_b_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('success_condition', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ab_tests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_tests'))
    )
    # ### end Alembic commands ###
