"""Normalize enum casing

Revision ID: d1ab84444c90
Revises: 6365773a1fff
Create Date: 2025-09-26 20:56:11.946948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ab84444c90'
down_revision: Union[str, None] = '6365773a1fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename UserLang enums
    op.execute("ALTER TYPE user_lang_enum RENAME VALUE 'EN' to 'en'")
    op.execute("ALTER TYPE user_lang_enum RENAME VALUE 'DE' to 'de'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rollback (reverse renames)
    op.execute("ALTER TYPE user_lang_enum RENAME VALUE 'en' TO 'EN'")
    op.execute("ALTER TYPE user_lang_enum RENAME VALUE 'de' TO 'DE'")
    # ### end Alembic commands ###
