"""replace userprefs with userprofile and usergoals

Revision ID: d2400ff2d226
Revises: 141674d969ac
Create Date: 2026-07-11 02:18:37.413523+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2400ff2d226'
down_revision: Union[str, None] = '141674d969ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'timezone', server_default=None)
    op.create_table('user_goals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight_target', sa.Float(), nullable=True),
    sa.Column('calories_target', sa.Integer(), nullable=True),
    sa.Column('steps_target', sa.Integer(), nullable=True),
    sa.Column('sleep_minutes_target', sa.Integer(), nullable=True),
    sa.Column('protein_target', sa.Integer(), nullable=True),
    sa.Column('fat_target', sa.Integer(), nullable=True),
    sa.Column('carbs_target', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_goals')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_goals_user_id'))
    )
    # Backfill:
    op.execute("INSERT INTO user_goals (user_id) SELECT id FROM users")

    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_system', postgresql.ENUM('metric', 'imperial', name='unit_system_enum', create_type=False), nullable=False),
    sa.Column('hour_cycle', sa.Enum('h12', 'h23', name='hour_cycle_enum'), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('sex', sa.Enum('m', 'f', name='sex_enum'), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("birth_date > '1900-12-31' AND birth_date < CURRENT_DATE", name=op.f('ck_user_profiles_birth_date_range')),
    sa.CheckConstraint('num_nonnulls(city, country, latitude, longitude) IN (0, 4)', name=op.f('ck_user_profiles_location_all_or_none')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    # Backfill:
    op.execute("""
        INSERT INTO user_profiles (user_id, unit_system, hour_cycle)
        SELECT id, units, 'h12' from users
""")
    op.drop_table('user_preferences')
    op.drop_column('users', 'country')
    op.drop_column('users', 'city')
    op.drop_column('users', 'lang')
    op.execute("DROP TYPE user_lang_enum")
    op.drop_column('users', 'units')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE user_lang_enum AS ENUM ('en', 'de')")
    op.add_column('users', sa.Column('units', postgresql.ENUM('metric', 'imperial', name='unit_system_enum'), server_default=sa.text("'imperial'::unit_system_enum"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('lang', postgresql.ENUM('en', 'de', name='user_lang_enum'), server_default=sa.text("'en'::user_lang_enum"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=100), server_default=sa.text("'Chicago'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('country', sa.VARCHAR(length=3), server_default=sa.text("'US'::character varying"), autoincrement=False, nullable=False))
    op.create_table('user_preferences',
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    op.drop_table('user_profiles')
    op.drop_table('user_goals')
    op.execute("DROP TYPE hour_cycle_enum")
    op.execute("DROP TYPE sex_enum")
    # ### end Alembic commands ###
