"""make title (leetcode) & desc (time_entries) nullable

Revision ID: d6f785b5f77b
Revises: 83ed6bf2fb12
Create Date: 2026-02-02 23:17:48.009331+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f785b5f77b'
down_revision: Union[str, None] = '83ed6bf2fb12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leet_code_records', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('time_entries', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('time_entries', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('leet_code_records', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
