"""Remove price from & add other fields to Product model

Revision ID: e5026ac2b998
Revises: 6d3333a77232
Create Date: 2025-06-18 18:27:45.169142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5026ac2b998'
down_revision: Union[str, None] = '6d3333a77232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('product', sa.Column('unit_type', sa.String(length=20), nullable=False, server_default='g'))
    op.add_column('product', sa.Column('calories_per_100g', sa.Float(), nullable=True))
    op.drop_column('product', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('product', 'calories_per_100g')
    op.drop_column('product', 'unit_type')
    op.drop_column('product', 'category')
    # ### end Alembic commands ###
