"""initial schema

Revision ID: e6625eaec776
Revises: 
Create Date: 2026-01-21 21:56:35.415274+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6625eaec776'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_records',
    sa.Column('api_called', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('call_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_call_records')),
    sa.UniqueConstraint('api_called', 'date', name='uq_api_called_date')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'USER', name='user_role_enum'), nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='America/Chicago', nullable=False),
    sa.Column('lang', sa.Enum('en', 'de', name='user_lang_enum'), nullable=False),
    sa.Column('city', sa.String(length=100), server_default='Chicago', nullable=False),
    sa.Column('country', sa.String(length=3), server_default='US', nullable=False),
    sa.Column('units', sa.Enum('metric', 'imperial', name='unit_system_enum'), server_default='imperial', nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('daily_metrics',
    sa.Column('entry_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('wake_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sleep_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sleep_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('calories >= 0', name=op.f('ck_daily_metrics_ck_calories_non_negative')),
    sa.CheckConstraint('steps >= 0', name=op.f('ck_daily_metrics_ck_steps_non_negative')),
    sa.CheckConstraint('weight > 0', name=op.f('ck_daily_metrics_ck_weight_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_metrics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_metrics'))
    )
    op.create_index('ix_user_entry_datetime', 'daily_metrics', ['user_id', 'entry_datetime'], unique=False)
    op.create_table('leet_code_records',
    sa.Column('leetcode_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty_enum'), nullable=False),
    sa.Column('language', sa.Enum('PYTHON', 'JS', 'CPP', 'C', name='language_enum'), nullable=False),
    sa.Column('status', sa.Enum('SOLVED', 'ATTEMPTED', 'REVIEWED', name='lcstatus_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leet_code_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leet_code_records'))
    )
    op.create_table('pillars',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pillars_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pillars')),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_pillar_name')
    )
    op.create_table('products',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.Enum('FRUITS', 'VEGETABLES', 'LEGUMES', 'GRAINS', 'BAKERY', 'DAIRY_EGGS', 'MEATS', 'SEAFOOD', 'FATS_OILS', 'SNACKS', 'SWEETS', 'BEVERAGES', 'CONDIMENTS_SAUCES', 'PROCESSED_CONVENIENCE', 'SUPPLEMENTS', name='product_category_enum'), nullable=False),
    sa.Column('barcode', sa.String(length=32), nullable=True),
    sa.Column('net_weight', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('unit_type', sa.Enum('G', 'KG', 'OZ', 'LB', 'ML', 'L', 'FL_OZ', 'EA', name='unit_enum'), nullable=False),
    sa.Column('calories_per_100g', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('calories_per_100g >= 0', name=op.f('ck_products_ck_product_calories_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_products_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('user_id', 'barcode', name='uq_user_product_barcode'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_product_name')
    )
    op.create_table('shopping_lists',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shopping_lists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_lists'))
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tags_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_tag_name')
    )
    op.create_table('tasks',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority_enum'), nullable=True),
    sa.Column('is_frog', sa.Boolean(), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(is_frog = true AND priority IS NULL) OR (NOT is_frog AND priority IS NOT NULL)', name=op.f('ck_tasks_ck_frog_priority_mutually_exclusive')),
    sa.CheckConstraint('NOT is_frog OR due_date IS NOT NULL', name=op.f('ck_tasks_ck_task_frog_requires_due_date')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_task_name')
    )
    op.create_table('time_entries',
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('duration_minutes > 0', name=op.f('ck_time_entries_ck_time_entry_duration_positive')),
    sa.CheckConstraint('ended_at > started_at', name=op.f('ck_time_entries_ck_ended_after_started')),
    sa.CheckConstraint('length(category) > 0', name=op.f('ck_time_entries_ck_time_entry_category_non_empty')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_time_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_entries'))
    )
    op.create_table('habits',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('EXPERIMENTAL', 'ESTABLISHED', name='status_enum'), nullable=True),
    sa.Column('established_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promotion_threshold', sa.Float(), nullable=True),
    sa.Column('target_frequency', sa.Integer(), nullable=False),
    sa.Column('pillar_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('promotion_threshold is NULL OR (promotion_threshold >= 0 AND promotion_threshold <= 1.0)', name=op.f('ck_habits_ck_promotion_threshold_range_0_1')),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], name=op.f('fk_habits_pillar_id_pillars')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habits')),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_habit_name')
    )
    op.create_table('shopping_list_items',
    sa.Column('quantity_wanted', sa.Integer(), nullable=False),
    sa.Column('shopping_list_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity_wanted > 0', name=op.f('ck_shopping_list_items_ck_shopping_quantity_wanted_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_shopping_list_items_product_id_products')),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], name=op.f('fk_shopping_list_items_shopping_list_id_shopping_lists')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shopping_list_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_list_items'))
    )
    op.create_table('task_tags',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_task_tags_tag_id_tags')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_tags_task_id_tasks')),
    sa.PrimaryKeyConstraint('task_id', 'tag_id', name=op.f('pk_task_tags'))
    )
    op.create_table('transactions',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_at_scan', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price_at_scan >= 0', name=op.f('ck_transactions_ck_transaction_price_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_transactions_ck_transaction_quantity_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_transactions_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_table('habit_completions',
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('fk_habit_completions_habit_id_habits')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_habit_completions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_habit_completions'))
    )
    op.create_table('habit_tags',
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('fk_habit_tags_habit_id_habits')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_habit_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('habit_id', 'tag_id', name=op.f('pk_habit_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habit_tags')
    op.drop_table('habit_completions')
    op.drop_table('transactions')
    op.drop_table('task_tags')
    op.drop_table('shopping_list_items')
    op.drop_table('habits')
    op.drop_table('time_entries')
    op.drop_table('tasks')
    op.drop_table('tags')
    op.drop_table('shopping_lists')
    op.drop_table('products')
    op.drop_table('pillars')
    op.drop_table('leet_code_records')
    op.drop_index('ix_user_entry_datetime', table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_table('users')
    op.drop_table('api_call_records')
    # ### end Alembic commands ###
