"""add ondelete cascade for task_links

Revision ID: f5e12167e6d6
Revises: c09c7a73ab1e
Create Date: 2026-02-21 01:17:13.033438+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e12167e6d6'
down_revision: Union[str, None] = 'c09c7a73ab1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_links_supertask_id_tasks'), 'task_links', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_links_subtask_id_tasks'), 'task_links', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_links_subtask_id_tasks'), 'task_links', 'tasks', ['subtask_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_task_links_supertask_id_tasks'), 'task_links', 'tasks', ['supertask_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_task_links_supertask_id_tasks'), 'task_links', type_='foreignkey')
    op.drop_constraint(op.f('fk_task_links_subtask_id_tasks'), 'task_links', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_links_subtask_id_tasks'), 'task_links', 'tasks', ['subtask_id'], ['id'])
    op.create_foreign_key(op.f('fk_task_links_supertask_id_tasks'), 'task_links', 'tasks', ['supertask_id'], ['id'])
    # ### end Alembic commands ###
