"""make tasks sort_key col collation c

Revision ID: ffd311d8eaae
Revises: 895b04060fbe
Create Date: 2026-05-26 23:15:10.218679+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd311d8eaae'
down_revision: Union[str, None] = '895b04060fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE tasks ALTER COLUMN sort_key TYPE varchar COLLATE "C";')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE tasks ALTER COLUMN sort_key TYPE varchar COLLATE "default";')
    # ### end Alembic commands ###
