from typing import Any, Callable, TypeVar

from app.modules.auth.models import User

_F = TypeVar("_F", bound=Callable[..., Any])

class UserMixin:
    @property
    def is_authenticated(self) -> bool: ...
    @property
    def is_active(self) -> bool: ...
    @property
    def is_anonymous(self) -> bool: ...
    def get_id(self) -> str: ...

class LoginManager:
    login_view: str | None
    def __init__(self, app: Any | None = None) -> None: ...
    def init_app(self, app: Any) -> None: ...
    def user_loader(self, callback: _F) -> _F: ...

def login_user(user: Any, remember: bool = False, force: bool = False) -> bool: ...
def logout_user() -> None: ...

current_user: User
