"""2025_11_13 add target_frequency to habit model

Revision ID: 0bcefc75a41c
Revises: 213c71a1b8db
Create Date: 2025-11-13 17:21:49.492629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bcefc75a41c'
down_revision: Union[str, None] = '213c71a1b8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('target_frequency', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'target_frequency')
    # ### end Alembic commands ###
