"""Add ended_at column to time entries

Revision ID: 39bbb35c76b2
Revises: 8f22ee57834d
Create Date: 2025-08-28 00:08:18.849414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39bbb35c76b2'
down_revision: Union[str, None] = '8f22ee57834d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeentry', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))

    # Backfill existing rows using started_at + duration
    op.execute("""
        UPDATE timeentry
        SET ended_at = started_at + (duration || ' minutes')::interval
        WHERE ended_at IS NULL
    """)

    # Then enforce non-null
    op.alter_column('timeentry', 'ended_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeentry', 'ended_at')
    # ### end Alembic commands ###
