"""Add LeetCodeRecord model

Revision ID: 6e90ad885f9c
Revises: b1ff504a81a6
Create Date: 2025-09-01 00:41:21.638029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e90ad885f9c'
down_revision: Union[str, None] = 'b1ff504a81a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leetcoderecord',
    sa.Column('leetcode_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('language', sa.Enum('PYTHON', 'JS', 'CPP', 'C', name='language'), nullable=False),
    sa.Column('status', sa.Enum('SOLVED', 'ATTEMPTED', 'REVIEWED', name='lcstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leetcoderecord')
    # ### end Alembic commands ###
