"""Add UserMixin from Flask-Login

Revision ID: 77bba107df6b
Revises: 5bb8f2c2d612
Create Date: 2025-07-31 09:51:42.812011

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '77bba107df6b'
down_revision: Union[str, None] = '5bb8f2c2d612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=256), 
    nullable=False, server_default='TEMP_HASH'))

    # Remember: server_default persists, so we need to then return it to None
    op.alter_column('user', 'password_hash', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
