"""Add user language field

Revision ID: 8f22ee57834d
Revises: 726ec630c801
Create Date: 2025-08-20 01:21:59.435326

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f22ee57834d'
down_revision: Union[str, None] = '726ec630c801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lang', sa.String(length=20), server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lang')
    # ### end Alembic commands ###
