"""empty message

Revision ID: 984d50204db9
Revises: d5ea1dfc7911
Create Date: 2026-01-21 20:23:15.241702+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984d50204db9'
down_revision: Union[str, None] = 'd5ea1dfc7911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column(
        'api_call_records',
        'updated_at',
        existing_type=sa.DateTime(timezone=True),
        nullable=True,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
