"""Add entry_datetime (composite index too), sleep_duration_minutes to DailyEntry

Revision ID: 985949b21670
Revises: 18aaa82451e0
Create Date: 2025-10-26 20:26:03.511307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985949b21670'
down_revision: Union[str, None] = '18aaa82451e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_entries', sa.Column('entry_datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('daily_entries', sa.Column('sleep_duration_minutes', sa.Integer(), nullable=True))
    op.create_index('ix_user_entry_datetime', 'daily_entries', ['user_id', 'entry_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_entry_datetime', table_name='daily_entries')
    op.drop_column('daily_entries', 'sleep_duration_minutes')
    op.drop_column('daily_entries', 'entry_datetime')
    # ### end Alembic commands ###
