"""Add quantity_wanted column for shopping list items

Revision ID: a4934c137134
Revises: 35dae74394e1
Create Date: 2025-09-08 14:20:33.289509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4934c137134'
down_revision: Union[str, None] = '35dae74394e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppinglistitem', sa.Column('quantity_wanted', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shoppinglistitem', 'quantity_wanted')
    # ### end Alembic commands ###
