"""remove habit status, threshold defaults, make nullable

Revision ID: bace352c9c4a
Revises: d1ab84444c90
Create Date: 2025-09-28 23:28:57.737329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bace352c9c4a'
down_revision: Union[str, None] = 'd1ab84444c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('habit', 'status',
               existing_type=postgresql.ENUM('EXPERIMENTAL', 'ESTABLISHED', name='status_enum'),
               nullable=True,
               server_default=None,
               existing_server_default=sa.text("'EXPERIMENTAL'::status_enum"))
    op.alter_column('timeentry', 'duration_minutes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeentry', 'duration_minutes',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('habit', 'status',
               existing_type=postgresql.ENUM('EXPERIMENTAL', 'ESTABLISHED', name='status_enum'),
               nullable=False,
               existing_server_default=sa.text("'EXPERIMENTAL'::status_enum"))
    # ### end Alembic commands ###
