"""add Pillar with relationship to habits, catch up

Revision ID: db86cc7063fc
Revises: fb4bf56d8ea0
Create Date: 2026-01-21 19:26:36.659574+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db86cc7063fc'
down_revision: Union[str, None] = 'fb4bf56d8ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pillars',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pillars_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pillars')),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_pillar_name')
    )
    op.alter_column('api_call_records', 'call_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('api_call_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('api_call_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('uq_apicallrecord_api_called'), 'api_call_records', type_='unique')
    op.alter_column('daily_metrics', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('daily_metrics', 'steps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'calories',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'wake_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('daily_metrics', 'sleep_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('daily_metrics', 'sleep_duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('daily_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('fk_dailyentry_user_id_user'), 'daily_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('fk_daily_metrics_user_id_users'), 'daily_metrics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('habit_completions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('habit_completions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('fk_habitcompletion_user_id_user'), 'habit_completions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_habit_completions_user_id_users'), 'habit_completions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('habits', sa.Column('pillar_id', sa.Integer(), nullable=False))
    op.alter_column('habits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('habits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('uq_habit_name'), 'habits', type_='unique')
    op.drop_constraint(op.f('fk_habit_user_id_user'), 'habits', type_='foreignkey')
    op.create_foreign_key(op.f('fk_habits_user_id_users'), 'habits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_habits_pillar_id_pillars'), 'habits', 'pillars', ['pillar_id'], ['id'])
    op.alter_column('leet_code_records', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('leet_code_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('leet_code_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('fk_leetcoderecord_user_id_user'), 'leet_code_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_leet_code_records_user_id_users'), 'leet_code_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('uq_product_barcode'), 'products', type_='unique')
    op.drop_constraint(op.f('fk_product_user_id_user'), 'products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_products_user_id_users'), 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('shopping_list_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('shopping_list_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('fk_shoppinglistitem_user_id_user'), 'shopping_list_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shopping_list_items_user_id_users'), 'shopping_list_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('shopping_lists', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('shopping_lists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('shopping_lists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('fk_shoppinglist_user_id_user'), 'shopping_lists', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shopping_lists_user_id_users'), 'shopping_lists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tags', 'scope',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('uq_tag_name'), 'tags', type_='unique')
    op.drop_constraint(op.f('fk_tag_user_id_user'), 'tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tags_user_id_users'), 'tags', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tasks', 'is_frog',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tasks', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('uq_task_name'), 'tasks', type_='unique')
    op.drop_constraint(op.f('fk_task_user_id_user'), 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_user_id_users'), 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('time_entries', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('time_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('time_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('fk_timeentry_user_id_user'), 'time_entries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_time_entries_user_id_users'), 'time_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('fk_transaction_user_id_user'), 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transactions_user_id_users'), 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('uq_user_username'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_user_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('fk_transactions_user_id_users'), 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transaction_user_id_user'), 'transactions', 'users', ['user_id'], ['id'])
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('fk_time_entries_user_id_users'), 'time_entries', type_='foreignkey')
    op.create_foreign_key(op.f('fk_timeentry_user_id_user'), 'time_entries', 'users', ['user_id'], ['id'])
    op.alter_column('time_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('time_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('time_entries', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_constraint(op.f('fk_tasks_user_id_users'), 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_task_user_id_user'), 'tasks', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('uq_task_name'), 'tasks', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tasks', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tasks', 'is_frog',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('fk_tags_user_id_users'), 'tags', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tag_user_id_user'), 'tags', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('uq_tag_name'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('tags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tags', 'scope',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(op.f('fk_shopping_lists_user_id_users'), 'shopping_lists', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shoppinglist_user_id_user'), 'shopping_lists', 'users', ['user_id'], ['id'])
    op.alter_column('shopping_lists', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('shopping_lists', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('shopping_lists', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(op.f('fk_shopping_list_items_user_id_users'), 'shopping_list_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_shoppinglistitem_user_id_user'), 'shopping_list_items', 'users', ['user_id'], ['id'])
    op.alter_column('shopping_list_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('shopping_list_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('fk_products_user_id_users'), 'products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_user_id_user'), 'products', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('uq_product_barcode'), 'products', ['barcode'], postgresql_nulls_not_distinct=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('fk_leet_code_records_user_id_users'), 'leet_code_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_leetcoderecord_user_id_user'), 'leet_code_records', 'users', ['user_id'], ['id'])
    op.alter_column('leet_code_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('leet_code_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('leet_code_records', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_constraint(op.f('fk_habits_pillar_id_pillars'), 'habits', type_='foreignkey')
    op.drop_constraint(op.f('fk_habits_user_id_users'), 'habits', type_='foreignkey')
    op.create_foreign_key(op.f('fk_habit_user_id_user'), 'habits', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('uq_habit_name'), 'habits', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('habits', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('habits', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('habits', 'pillar_id')
    op.drop_constraint(op.f('fk_habit_completions_user_id_users'), 'habit_completions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_habitcompletion_user_id_user'), 'habit_completions', 'users', ['user_id'], ['id'])
    op.alter_column('habit_completions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('habit_completions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('fk_daily_metrics_user_id_users'), 'daily_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dailyentry_user_id_user'), 'daily_metrics', 'users', ['user_id'], ['id'])
    op.alter_column('daily_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('daily_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('daily_metrics', 'sleep_duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'sleep_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('daily_metrics', 'wake_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('daily_metrics', 'calories',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'steps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'weight',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.create_unique_constraint(op.f('uq_apicallrecord_api_called'), 'api_call_records', ['api_called', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('api_call_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('api_call_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('api_call_records', 'call_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_table('pillars')
    # ### end Alembic commands ###
