"""Add timezone column to 'user', add default text for dailyintention

Revision ID: e682fc5fb1e7
Revises: 0336e9ba736a
Create Date: 2025-08-17 18:03:24.606471

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e682fc5fb1e7'
down_revision: Union[str, None] = '0336e9ba736a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('timezone', sa.String(length=50), server_default='America/Chicago', nullable=False))
    op.alter_column('dailyintention', 'intention', server_default="What's your focus today?")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    op.alter_column('dailyintention', 'intention', server_default=None)
    # ### end Alembic commands ###
