"""empty message

Revision ID: eb520bb02835
Revises: 9d170ab1d15b
Create Date: 2026-01-21 21:47:50.479766+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb520bb02835'
down_revision: Union[str, None] = '9d170ab1d15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_metrics', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('daily_metrics', 'steps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'calories',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_metrics', 'wake_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('daily_metrics', 'sleep_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('daily_metrics', 'sleep_duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_metrics', 'sleep_duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'sleep_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('daily_metrics', 'wake_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('daily_metrics', 'calories',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'steps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_metrics', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
