"""Quotes for the home page daily card, OCR'd from the booklet (2026-07).

(quote, author) tuples; author is None where the card had no attribution.
# GAP = OCR dropped words and the original is unknown — check the physical card.
# FILLED = missing words restored from the standard/famous version of the quote.
"""

QUOTES: list[tuple[str, str | None]] = [
    ("No man can walk out on his own story.", "Totally Not Clint Eastwood"),
    ("Common sense will not accomplish great things. Simply become insane and desperate.", "Nabeshima Naoshige"),
    ("I was waiting for something extraordinary to happen, but as the years wasted on, nothing ever did unless I caused it", "Charles Bukowski"),
    ("The torment of precautions often exceeds the dangers to be avoided. It is sometimes better to abandon oneself to destiny.", "Napolean Bonaparte"),
    ("Doors are made to be opened; locks are made to fit a key.", None),
    ("Make your own sunshine.", None),
    ("Be who you always wanted to be.", None),
    ("Shoot for the moon. Even if you miss, you'll land among the stars.", "Les Brown"),
    ("Some days there won't be a song in your heart. Sing anyway.", "Emory Austin"),
    ("If you can find a path with no obstacles, it probably doesn't lead anywhere.", "Frank A. Clark"),
    ("Opportunities multiply as they are seized.", "Sun Tzu"),
    ("First say to yourself what you would be; and then do what you have to do.", "Epictetus"),
    ("Whether you think you can or think you can't, you're right.", "Henry Ford"),
    ("Live life off the map and be your own compass.", None),
    ("Look at everything as though you were seeing it for the first or last time.", "Betty Smith"),
    ("When you come to a roadblock, take a detour.", "Mary Kay Ash"),
    ("You can't expect to hit the jackpot if you don't put a few nickels in the machine.", "Flip Wilson"),
    ("What matters is to live in the present, the moment is now.", "Sathya Sai Baba"),  # GAP
    ("If you're going through hell, keep going.", "Winston Churchill"),
    ("You can't wait for inspiration. You have to go after it with a club.", "Jack London"),
    ("If you wait, all that happens is that you get older.", "Mario Andretti"),
    ("Nobody can hold you back.", None),
    ("It's important not to limit yourself. You can do whatever you really love to do, no matter what it is.", "Ryan Gosling"),
    ("Keep calm and seize the day.", None),
    ("Do not pray for an easy life. Pray for the strength to endure a difficult one.", "Bruce Lee"),
    ("Life shrinks or expands according to one's courage.", "Anais Nin"),
    ("If you're already walking on thin ice, you might as well dance.", "Proverb"),
    ("If the wind will serve, take to the...", "Latin proverb"),  # GAP: standard proverb is "If the wind will not serve, take to the oars"
    ("Look at life through the windshield, not the rear-view mirror.", "Byrd Baggett"),
    ("Every artist was first an amateur.", "Ralph Waldo Emerson"),
    ("Don't get your knickers in a knot. Nothing is solved and it just makes you walk funny.", "Kathryn Carpenter"),
    ("The best way to make your dreams come true is to wake up.", "Paul Valery"),
    ("You're never lost; you're just discovering new places.", None),
    ("Go and get it!", None),
    ("I'd rather regret the things I've done than regret the things I haven't done.", "Lucille Ball"),  # FILLED
    ("...about learning to dance in the rain.", "Anonymous"),  # GAP: likely "Life isn't about waiting for the storm to pass, it's about learning to dance in the rain"
    ("Carpe diem.", None),
    ("With the new day comes new strength and new thoughts.", "Eleanor Roosevelt"),
    ("Life is a shipwreck, but we must not forget to sing in the lifeboats.", "Voltaire"),
    ("Life isn't about finding yourself. Life is about creating yourself.", "George Bernard Shaw"),
    ("You're the blacksmith of your own happiness.", "Swedish proverb"),
    ("Do what you can, with what you have, where you are.", "Theodore Roosevelt"),  # FILLED
    ("Look at life from unexpected angles today.", None),
    ("The envious moment is flying now while we're speaking: seize the day.", "Horace"),
    ("Scared is what you're feeling; brave is what you're doing.", "Emma Donoghue"),
    ("How wonderful it is that nobody need wait a single moment before starting to improve the world.", "Anne Frank"),
    ("A mind is like a parachute. It doesn't work if it is not open.", "Frank Zappa"),
    ("Whoever is happy will make others happy too.", "Anne Frank"),
    ("The secret of getting ahead is getting started.", "Anonymous"),
    ("Enjoy today and don't worry about tomorrow.", None),
    ("I have found that if you love life, life will love you back.", "Arthur Rubinstein"),
    ("Life is simple, it's just not easy.", "Anonymous"),
    ("Act as if what you do makes a difference. It does.", "William James"),
    ("Make an impression!", None),
    ("It's never too late — never too late to start over, never too late to be happy.", "Jane Fonda"),
    ("Live your questions now, and perhaps even without knowing it, you will live along some distant day into your answers.", "Rainer Maria Rilke"),
    ("Live today, for tomorrow it will all be history.", "Proverb"),
    ("Change your life today. Don't gamble on the future, act now, without delay.", "Simone de Beauvoir"),
    ("I couldn't wait for success, so I went ahead without it.", "Jonathan Winters"),
    ("You can have anything you want if you will give up the belief that you can't have it.", "Robert Anthony"),
    ("Difficulties strengthen the mind, as labour does the body.", "Seneca the Younger"),
    ("Flowers that grow up through the cracks...", None),  # GAP: fragment only
    ("To rest is to rust. Stay shiny and bright!", None),
    ("For myself, I am an optimist — it does not seem to be much use being anything else.", "Winston Churchill"),
    ("Life begins at the end of your comfort zone.", "Neale Donald Walsch"),
    ("Be a child again today and spread some mischief!", None),
    ("Just be yourself.", None),
    ("Life is not a rehearsal: enjoy the...", None),  # GAP: last word missing
    ("You are perfectly cast in your life. I can't imagine anyone but you in the role. Go play.", "Lin-Manuel Miranda"),
    ("It's OK to have butterflies in your stomach. Just get them to fly in formation.", "Rob Gilbert"),
    ("You can't turn back the clock, but you can wind it up again.", "Bonnie Prudden"),
    ("Opportunity is missed by most people because it is dressed in overalls and looks like work.", "Thomas Edison"),
    ("One joy scatters a hundred griefs.", "Chinese proverb"),
    ("The wise does at once what the fool does at last.", "Baltasar Gracian"),
    ("Create your own destiny.", "Daniel Radcliffe"),
    ("Be happy. It's one way of being wise.", "Colette"),
    ("When's the best time to start? Right now!", None),
    ("Talk to someone new. You could make their day and they might make yours.", None),  # FILLED: final word inferred
    ("When it is darkest, men see the stars.", "Ralph Waldo Emerson"),
    ("A journey of a thousand miles begins with a single step.", "Lao Tzu"),
    ("Do your thing and don't care if they like it.", "Tina Fey"),
    ("Dress to impress and be the best you can be.", None),
    ("Make new connections today!", None),
    ("Every dawn is a new beginning, a time to start a new story.", None),
    ("Welcome today's challenges.", None),
    ("There are always flowers for those who want to see them.", "Henri Matisse"),
    ("Today is a blank page — what are you going to write on it?", None),
    ("Opportunities are like sunrises. If you wait too long, you miss them.", "William Arthur Ward"),
    ("To me, every hour of the day and night is an unspeakably perfect miracle.", "Walt Whitman"),
    ("Nothing will work unless you do.", "Maya Angelou"),
    ("Build something new today, however small.", None),
    ("If your ship doesn't come in, swim out to it.", "Jonathan Winters"),
    ("Luck is a dividend of sweat. The more you sweat, the luckier you get.", "Ray Kroc"),  # FILLED
    ("You are never too old to set another goal or to dream a new dream.", "Les Brown"),
    ("With the past, I have nothing to do; nor with the future. I live now.", "Ralph Waldo Emerson"),
    ("Happiness is a way of travel, not a destination.", "Roy M. Goodman"),
    ('Life is a helluva lot more fun if you say "yes" rather than "no".', "Richard Branson"),
    ("Our greatest glory is not in never falling, but in rising every time we fall.", "Confucius"),
    ("Without obstacles, life would just be a race — and that wouldn't be half as much fun.", None),
    ("The man who removes a mountain begins by carrying away small stones.", "Chinese proverb"),
    ("You can't use up creativity. The more you use, the more you have.", "Maya Angelou"),
    ("To succeed in life you need three things: a wishbone, a backbone and a funny bone.", "Reba McEntire"),
    ("Make every minute count.", None),
    ("Turn your hopes into realities.", None),
    ("Show the world what you're made of.", None),
    ("Life is either a daring adventure or nothing.", "Helen Keller"),
    ("The best way out is always through.", "Robert Frost"),
    ("The season of failure is the best time for sowing the seeds of success.", "Paramahansa Yogananda"),
    ("There are no shortcuts to any place worth going.", "Beverly Sills"),
]
