/* tslint:disable */
/* eslint-disable */
// Generated by scripts/gen_enum_labels.py - do not edit.
import type { UnitEnum, ProductCategoryEnum, MealEnum } from './apiTypes';
export const UNIT_LABELS: Record<UnitEnum, string> = {
  "g": "g",
  "kg": "kg",
  "oz": "oz",
  "lb": "lb",
  "ml": "ml",
  "l": "l",
  "fl_oz": "fl oz",
  "ea": "ea"
};
export const PRODUCT_CATEGORY_LABELS: Record<ProductCategoryEnum, string> = {
  "fruits": "Fruits",
  "vegetables": "Vegetables",
  "legumes": "Legumes",
  "grains": "Grains",
  "bakery": "Bakery",
  "dairy_eggs": "Dairy & Eggs",
  "meats": "Meats",
  "seafood": "Seafood",
  "fats_oils": "Fats & Oils",
  "snacks": "Snacks",
  "sweets": "Sweets",
  "beverages": "Beverages",
  "condiments_sauces": "Condiments & Sauces",
  "processed_convenience": "Processed & Convenience",
  "supplements": "Supplements"
};
export const MEAL_LABELS: Record<MealEnum, string> = {
  "breakfast": "Breakfast",
  "morning_snack": "Morning Snack",
  "lunch": "Lunch",
  "afternoon_snack": "Afternoon Snack",
  "supper": "Supper",
  "pm_snack": "Pm Snack"
};
