
import importlib
import json
import pkgutil
import re
from enum import StrEnum
from pathlib import Path

import app.modules

with_labels = []
for info in pkgutil.iter_modules(app.modules.__path__):
    # a module obj is what the file becomes once imported
    # every top-level name in models.py is an attr on "models" here?
    models = importlib.import_module(f"app.modules.{info.name}.models")
    # for v in vars(models): # {name: object} for everything defined/imported there?
    for name, obj in vars(models).items():
        if isinstance(obj, type) and issubclass(obj, StrEnum) and obj.__module__ == models.__name__ and hasattr(obj, "label"):
            with_labels.append(obj)

# Walk the members
my_dicts = {enum_cls.__name__: {m.value: m.label for m in enum_cls} for enum_cls in with_labels}

# Start writing to file
OUT = Path(__file__).resolve().parents[1] / "app/static_src/js/enumLabels.ts"

with open(OUT, "w", encoding="utf-8") as file:
    # Header line:
    file.write("/* tslint:disable */\n/* eslint-disable */\n")
    file.write("// Generated by scripts/gen_enum_labels.py - do not edit.\n")

    import_line = f"import type {{ { ", ".join(list(my_dicts)) } }} from './apiTypes';\n"
    file.write(import_line)

    for name, things in my_dicts.items():
        type_body = json.dumps(things, indent=2)
        # strip suffix then insert "_" before each capital letter?
        const_name = re.sub(r"(?<!^)(?=[A-Z])", "_", name.removesuffix("Enum")).upper()
        type_line = f"export const {const_name}_LABELS: Record<{name}, string> = "
        together = f"{type_line}{type_body};\n"
        file.write(together)

print(f"Saved typescript definitions to {OUT}")
